import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("http://122.45.170.200:8081"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "http://122.45.170.200:8081",
    siteName: "Your Site Name",
    locale: "en_US",
    type: "website",
  },
  // CSP 설정 추가
  other: {
    "Content-Security-Policy": "upgrade-insecure-requests",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto bg-white text-suldak-gray-900 ${inter.className}`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
