import { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-pretendard" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
